name: smart-estate

services:
  api:
    build:
      dockerfile: Dockerfile
    image: ghcr.io/damianwasik98/smart-estate-api:latest
    pull_policy: always
    container_name: smart-estate-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
    env_file: .env

  db:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s

volumes:
  db:
