name: Docker Image CI

on:
  push:
    branches: ["main"]
    tags: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          registry: "ghcr.io"
          username: damianwasik98
          password: ${{ secrets.WRITE_PACKAGES_TOKEN }}
      - name: Build and push Docker images to Container Registry
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          GIT_TAG=$(git describe --tags --abbrev=0 || echo "none")

          REGISTRY="ghcr.io/damianwasik98"
          IMAGE="smart-estate-api"
          DOCKER_IMAGE="$REGISTRY/$IMAGE"

          BASE_TAG="$DOCKER_IMAGE:$COMMIT_SHA"

          docker build . --file Dockerfile --tag "$BASE_TAG"
          docker push "$BASE_TAG"

          if [ "${GIT_TAG}" != "none" ]; then
            RELEASE_TAG="$DOCKER_IMAGE:$GIT_TAG"
            docker tag "$BASE_TAG" "$RELEASE_TAG"
            docker push "$RELEASE_TAG"
          fi

          LATEST_TAG="$DOCKER_IMAGE:latest"
          docker tag "$BASE_TAG" "$LATEST_TAG"
          docker push "$LATEST_TAG"
